### ISSUE TITLE
Importing avo-inspector package breaks SSR

### ISSUE THREAD

**Issue by diki** [avohq/js-avo-inspector#135]
Hello,

We at DeliveryHero are using avo-insector. Unfortunately `avo-inspector` npm package breaks SSR just with import statement

```js
// this statement breaks SSR
import { AvoInspector } from 'avo-inspector';
```

Error message is obfuscated but i think error happens because inspector object is constructed on import and needs an api-key. When there is no api-key it throws an error.

I think this issue can be fixed on your side with a `typeof window === undefined` check.

Can you please have a look.

Cheers!

**Comment by hugihlynsson** [comment]
Hi @diki! We definitely have opportunities to make this clearer in the readme but there is another Inspector package that's dedicated for SSR and service worker use here: https://github.com/avohq/ssr-web-avo-inspector
Could you try that our and see if it does the trick?

**Comment by hugihlynsson** [comment]
CC @alex-tpom6oh

**Comment by diki** [comment]
@hugihlynsson thanks for quick reply. I just tested ssr package, it works well.
 My question is can we safely replace `avo-inspector` package with `ssr-web-avo-inspector` package directly?

**Comment by hugihlynsson** [comment]
Good to hear! I believe the interface should be exactly the same and it should be a drop-in replacement. Let me know if you have any further thoughts or questions. If not, you're free to close this issue!
