### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by sshvaiko** [avohq/js-avo-inspector#38]
Hello, I'm trying to import Inspector this way in my React Native app:
`import * as Inspector from "avo-inspector";`

And getting this error:
```
error: Error: While trying to resolve module `avo-inspector` from file `/Users/stan/Projects/myApp/src/helpers/Analytics.js`, the package `/Users/stan/Projects/myApp/node_modules/avo-inspector/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/stan/Projects/myApp/node_modules/avo-inspector/dist-native/index.js`. Indeed, none of these files exist:

  * /Users/stan/Projects/myApp/node_modules/avo-inspector/dist-native/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * /Users/stan/Projects/myApp/node_modules/avo-inspector/dist-native/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
```

**Comment by tpom6oh** [comment]
Hi @sshvaiko, are you using the react native package  https://www.npmjs.com/package/react-native-avo-inspector?

**Comment by tpom6oh** [comment]
We manage a separate branch for React Native https://github.com/avohq/js-avo-inspector/tree/react-native-node-package

**Comment by sshvaiko** [comment]
Hello @tpom6oh, I'm using this package: https://www.npmjs.com/package/avo-inspector

Should I install it from a separate branch?

**Comment by tpom6oh** [comment]
Yes, it's definitely not clear that we have different packages for web and react native, thanks for bringing attention to that! I'll update the main readme to indicate.
In the meantime could you try removing the `avo-inspector` and installing `react-native-avo-inspector` instead and see if the problem persists?

**Comment by tpom6oh** [comment]
@sshvaiko have you had a chance to check this out?
