### ISSUE TITLE
Syntax Error IE 11

### ISSUE THREAD

**Issue by derekr** [avohq/js-avo-inspector#44]
In at least version 1.2.4 and 1.2.5 I've experienced a syntax error in IE 11. Not getting a full stack trace and difficult to debug given the capability of IE11s developer tools. 

![CleanShot 2020-11-14 at 14 51 16](https://user-images.githubusercontent.com/22249/99196141-42149480-273f-11eb-936c-89866a518e8d.png)

We're stuck at version 1.2.0 now until this is fixed. Was discovered when bumping the patch version to 1.2.4 (and trying 1.2.5 had the same issue).

**Comment by logason** [comment]
Thank you for reporting @derekr! We're working on a fix in #45

**Comment by logason** [comment]
Hey @derekr a fix is available in `1.2.6`. Could you try it out and verify if it resolves this issue?

**Comment by derekr** [comment]
@logason that seems to have fixed it! Thanks for the quick turn around.

**Comment by logason** [comment]
Awesome @derekr, thank you for acting fast on trying it out! 💃
