### ISSUE TITLE
[React Native] Warning of Avo using AsyncStorage from wrong package 

### ISSUE THREAD

**Issue by pedpess** [avohq/js-avo-inspector#91]
[`AvoStorage.ts`](https://github.com/avohq/js-avo-inspector/blob/ab24a86d4040d6124af13832f9a7069eecc89818/src/AvoStorage.ts#L32) file is currently using `AsyncStorage` from `react-native` package and that was extracted to another repo `@react-native-async-storage/async-storage` which should be the correct one. 

Would opening a PR and changing it suffice as a fix? If yes I could try to change it.

<img src="https://user-images.githubusercontent.com/14947502/179064691-c3231983-2fb9-45d4-911e-b0b18dd07701.jpg" width="600" height="800">

**Comment by hugihlynsson** [comment]
Hi @pedpess and thanks for letting us know about this issue! If you're up for fix this this that'd be great. We'll do your best to review it, get it merged and publish a new version. Just make sure that you base fix of the react-native branch: https://github.com/avohq/js-avo-inspector/tree/react-native-node-package

**Comment by pedpess** [comment]
Hi @hugihlynsson 👋🏻 , thanks for the reply, I have just made my fixes here https://github.com/avohq/js-avo-inspector/pull/92 , please let me know if anything else should be changed. Cheers

**Comment by alex-tpom6oh** [comment]
Migrated to "@react-native-async-storage/async-storage" in v 1.2.10, thanks for reporting
